export const Copy = {
  app: {
    name: 'Apnea Freediving',
    tagline: 'Train your breath hold with structure.',
    subtitle: 'Breathwork, Stamina & Apple Watch',
  },

  onboarding: {
    slides: [
      {
        title: 'Structured Breath-Hold Training',
        body: 'CO₂ and O₂ tables built around your personal best. Progress safely and measurably.',
        cta: 'Next',
      },
      {
        title: 'Personalized to Your PB',
        body: 'Enter your current static apnea PB. The app generates an 8-week progressive plan tuned to push you 15–25% further.',
        cta: 'Next',
      },
      {
        title: 'Wrist-Ready for Pool & Ocean',
        body: 'Apple Watch companion keeps your session on your wrist — haptic phase transitions, live timer, heart rate display.',
        cta: 'Next',
      },
      {
        title: 'Built by Divers, for Divers',
        body: 'Used by 2,800+ freedivers worldwide. Trusted by spearos and breathwork athletes at every level.',
        cta: 'Get Started',
      },
    ],
  },

  setup: {
    title: 'Set Your Personal Best',
    subtitle: 'We\'ll generate training tables around your current static apnea PB.',
    pbLabel: 'Static Apnea PB',
    pbPlaceholder: 'e.g. 3:30',
    goalLabel: 'Target Improvement',
    goalOptions: [
      { value: 0.1, label: '+10%', description: 'Conservative' },
      { value: 0.15, label: '+15%', description: 'Moderate' },
      { value: 0.20, label: '+20%', description: 'Recommended' },
      { value: 0.25, label: '+25%', description: 'Ambitious' },
    ],
    levelLabel: 'Experience Level',
    modeLabel: 'Preferred Training Mode',
    cta: 'Generate My Plan',
    skip: 'Skip for now',
  },

  home: {
    greeting: 'Ready to train.',
    quickStart: 'Quick Start',
    co2Label: 'CO₂ Table',
    o2Label: 'O₂ Table',
    maxLabel: 'Max Hold',
    spearoLabel: 'Spearfishing',
    myPlan: 'My Training Plan',
    noPlan: 'Set your PB to generate a personalized 8-week plan.',
    setupPlan: 'Set Up Plan',
    watchPromo: 'Train on your wrist with Apple Watch companion.',
    proPromo: 'Unlock personalized plans, adaptive tables & Apple Watch.',
    upgradeLabel: 'Upgrade to Pro',
    continuePlan: 'Continue Plan',
    weekProgress: 'Week {week} of 8',
    sessionsDone: '{n} sessions this week',
    pbDisplay: 'Current PB',
    targetDisplay: 'Target',
    streakLabel: 'Day Streak',
    totalSessions: 'Total Sessions',
  },

  training: {
    roundOf: 'Round {current} of {total}',
    holdPhase: 'HOLD',
    restPhase: 'REST',
    breathePhase: 'BREATHE',
    completePhase: 'COMPLETE',
    pauseLabel: 'Pause',
    resumeLabel: 'Resume',
    resetLabel: 'Reset',
    completeSession: 'Finish Session',
    effortPrompt: 'How did that feel?',
    effortLabels: ['Very Easy', 'Easy', 'Moderate', 'Hard', 'Max Effort'],
    nextRound: 'Next Round',
    sessionComplete: 'Session Complete',
    holdTotal: 'Total Hold Time',
    rounds: 'Rounds',
    avgHold: 'Avg Hold',
    personalBest: 'Personal Best',
    newPB: 'New Personal Best!',
    saveSession: 'Save Session',
    discardSession: 'Discard',
  },

  plan: {
    title: 'My 8-Week Plan',
    week: 'Week {n}',
    projectedPB: 'Projected PB',
    startWeek: 'Start Week {n}',
    currentWeek: 'Current Week',
    completed: 'Completed',
    dayLabels: ['Mon', 'Wed', 'Fri'],
    sessionsPerWeek: '3 sessions / week',
    adaptNote: 'Rate each session to adapt your plan.',
  },

  history: {
    title: 'Progress',
    noHistory: 'No sessions logged yet.\nStart your first training session.',
    recentSessions: 'Recent Sessions',
    pbHistory: 'PB Timeline',
    weeklyActivity: 'Weekly Activity',
    streakLabel: '{n}-day streak',
    totalTimeLabel: 'Total Hold Time',
    sessionCount: '{n} Sessions',
    pbGrowth: '+{n}% from start',
  },

  settings: {
    title: 'Settings',
    upgradePro: 'Upgrade to Pro',
    restorePurchases: 'Restore Purchases',
    appleWatch: 'Apple Watch',
    haptics: 'Haptic Feedback',
    sound: 'Sound Cues',
    defaultMode: 'Default Training Mode',
    units: 'Units',
    rateUs: 'Rate Us',
    contact: 'Contact Support',
    privacy: 'Privacy Policy',
    terms: 'Terms of Use',
    version: 'Version',
    proFeatures: [
      'Personalized 8-week training plans',
      'Adaptive table difficulty',
      'Apple Watch companion',
      'Spearfishing module',
      'Unlimited session history',
      'Advanced progress analytics',
    ],
    watchDescription: 'Live timer, haptic phase transitions, heart rate, and crown navigation — all on your wrist.',
    watchComingSoon: 'Apple Watch companion requires Apnea Freediving Pro.',
  },

  spearfishing: {
    title: 'Spearfishing Module',
    subtitle: 'Tables optimized for repetitive ocean dives.',
    surfaceInterval: 'Surface Interval',
    targetDepth: 'Target Depth',
    shoreDay: 'Shore Day Mode',
    safetyNote: 'Always dive with a buddy. Never dive alone.',
    proRequired: 'Spearfishing module is a Pro feature.',
  },
} as const;
